apiVersion: v1
kind: Pod
metadata:
  name: meupod
  labels:
    name: myapp
spec:
  containers:
  - name: web
    image: kubedevio/web-color:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
