apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-configuracao
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-configuracao
  template:
    metadata:
      labels:
        app: app-configuracao
    spec:
      containers:
      - name: app-configuracao
        image: kubedevio/app-variaveis-ambiente:v1
        ports:
        - containerPort: 3000
        env:
        - name: APP_NAME
          valueFrom:
            secretKeyRef:
              name: app-secret-valor
              key: APP_NAME_CONFIG
        - name: APP_VERSION
          valueFrom:
            secretKeyRef:
              name: app-secret-valor
              key: APP_VERSION_CONFIG
        - name: APP_AUTHOR
          valueFrom:
            secretKeyRef:
              name: app-secret-valor
              key: APP_AUTHOR_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: app-configuracao
spec:
  selector:
    app: app-configuracao
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000
