apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  APP_NAME: "UHJvZ3JhbWEgc2VjcmV0IG9wYXF1ZSAxLjA="
  APP_VERSION: "VjEuMCBTZWNyZXQgT3BhcXVl"
  APP_AUTHOR: "Ui5TZXR1YmFsIChyZW1pc2V0KQ=="
