apiVersion: apps/v1
kind: Deployment
metadata:
  name: livetcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livetcp
  template:
    metadata:
      labels:
        app: livetcp
    spec:
      containers:
      - name: livetcp
        image: debian:12
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3 # Número de segundos após o início do container para o liveness
          periodSeconds: 10 # Intervalo de tempo entre as verificações
          failureThreshold: 3 # Número de falhas pra considerar a aplicação não saudável
          successThreshold: 1 # Número de sucessos para zerar o failureThreshold (No liveness é 1)
          timeoutSeconds: 3 # Timeout da chamada
          terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: livetcp
spec:
  selector:
    app: livetcp
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000
