apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveexec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveexec
  template:
    metadata:
      labels:
        app: liveexec
    spec:
      containers:
      - name: liveexec
        image: debian:12
        command:
        - /bin/sh
        - -c
        args:
        - touch /tmp/health; sleep 600;
        ports:
        - containerPort: 3000
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/health
          initialDelaySeconds: 3 # Número de segundos após o início do container para o liveness
          periodSeconds: 10 # Intervalo de tempo entre as verificações
          failureThreshold: 3 # Número de falhas pra considerar a aplicação não saudável
          successThreshold: 1 # Número de sucessos para zerar o failureThreshold (No liveness é 1)
          timeoutSeconds: 3 # Timeout da chamada
          terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: liveexec
spec:
  selector:
    app: liveexec
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000
