apiVersion: v1
kind: Pod
metadata:
  name: exec
  labels:
    app: exec
spec:
  containers:
  - name: exec
    image: busybox
    command:
    - echo
    args:
    - "Hello World from kubernetes"
  restartPolicy: Never
